### ISSUE TITLE
Non manifold export with AMF exporter

### ISSUE THREAD

**Issue by z3dev** [jscad/io#12]
_From @hovissimo on February 5, 2016 22:2_

Source: https://gist.github.com/hovissimo/ce5366a35834c3690488

Result: http://imgur.com/KRkJ9UI (light blue shows discontinuities)

_Copied from original issue: Spiritdude/OpenJSCAD.org#126_

**Comment by z3dev** [comment]
This is basically the same as the STL import bug, as the same internat routine is used.

**Comment by kaosat-dev** [comment]
fixed by #34
