### ISSUE TITLE
OpenJSCAD stl generation error not present in openscad.

### ISSUE THREAD

**Issue by z3dev** [jscad/io#14]
_From @juergenboehm on January 5, 2016 23:13_

If one transforms the scad file

http://www.aviduratas.de/modelpart-025.scad

with openJSCAD one gets

http://www.aviduratas.de/openjscad.stl

transformed with openscad one gets

http://www.aviduratas.de/modelpart-025.stl

A review with netfabb shows, that modelpart-025.stl is correct (only "expected holes", where two polyhedra are connected by a single edge only).

But openjscad.stl contains severe errors, especially the following, where a triangle is inserted, that does not appear in the original .scad file:

http://www.aviduratas.de/openjscad-error.png

_Copied from original issue: Spiritdude/OpenJSCAD.org#115_

**Comment by z3dev** [comment]
_From @juergenboehm on January 10, 2016 1:15_

As I rearranged files on my homepage now the urls are

http://www.aviduratas.de/openjscad/modelpart-025.scad

and so on for the other files

**Comment by z3dev** [comment]
Pull request #107 contains some changes to CSG.js and openjscad.js. I ran some tests and all issues with T-junctions were resolved after making those changes.

If you need this fixed then please make the changes manually.

**Comment by kaosat-dev** [comment]
fixed by #34
