### ISSUE TITLE
Switch package managment to Lerna ?

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/io#21]
**what**: [Lerna](https://github.com/lerna) is tool for managing monorepos (like this one) ie one git repository containing lots of (usually related) package.

**why**: we need more automation, less manual work to tests, manage, update & publish packages

**long version**:
Right now there is a lot of manual work to manage the whole list of packages, and duplicated 
dependencies (a lot of them depend on CSG.js, or will be using the same unit testing tools, etc).
When I restructured the old monolithic code I already had Lerna in mind , so we already have a good base to start from, but like to keep tooling to a minimal, so I avoided adding Lerna as the main tool to manage this repo.

I will explore the ins and outs a bit more before actually proposing a switch, and will post information here in the meantime.
Discussion & questions, are , as always , very welcome

**Comment by z3dev** [comment]
Looks promising

**Comment by kaosat-dev** [comment]
So this might be needed sooner than expected:
- CI (travis) is more difficult to set up with sub packages: ie who runs the tests ? 
- where are the dependencies , a mix of root & subpackage? 
- why install duplicate dependencies for each package when testing ?
- each version change of a sub package should also trigger changes in the 'wrapper' package (packages/io) (perhaps we could get rid of that wrapper package altogether, any convenience it provides is cancelled out by the complexity it adds)

**Comment by kaosat-dev** [comment]
Also found some other monorepo tooling:
- https://github.com/Microsoft/web-build-tools/wiki/Rush

**Comment by kaosat-dev** [comment]
btw @z3dev I have experimented some more with Lerna, and it seems to do a great job for managing lots of small packages, I will do some more testing but it is on the right track

**Comment by kaosat-dev** [comment]
the bulk of this id being done and almost ready in PR #24

**Comment by kaosat-dev** [comment]
this is now done, closing
