### ISSUE TITLE
Add ability for deserializers to create CSG/CAG objects instead of just jscad code

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/io#3]
Currently, 
- serializers take **CSG/CAG** objects to output data that can be saved to disk
- deserializers take raw data from file formats and output **jscad CODE**

This asymmetrical nature is ok and useful but is limiting the use of the deserializers: if they also offered a mode to generate CSG/CAG objects we could do things in our jscad scripts such as

```javascript
const rawData= fs.readFileSync('PATH/TO/somePart.stl')
const myPart = difference(
  deserialize(rawData),
  cube(10)
)
```

>Edit : 30.10.2017
There has been lots of progress towards this, but it is not fully finished yet : 
- [x] amf deserializer
- [x] gcode deserializer
- [x] obj deserializer
- [x] stl deserializer
- [x] svg deserializer
- [ ] json deserializer

**Comment by z3dev** [comment]
Agreed, and the SVG 'parser' was written to support that possibility.

It's also why I wrote the JSON support. JSON is a standard payload for web servers. And CSG/CAG/etc can easily be serialized in and out.

Once I a complete Raspberry PI board, I don't need the JSCAD script. I just need the CSG.

**Comment by kaosat-dev** [comment]
This is starting to be put into place after trial and error & discussions with @z3dev  :
the svg-deserializer has the option to return CSG/CAG objects directly with a new option 
`{output: csg}`
https://github.com/jscad/io/blob/master/packages/svg-deserializer/test.js#L278

It is also planned to have a wrapper function to provide an api within jscad scripts:
something like this: 
```javascript
const myCSG = deserialize(rawData, {source:'svg'})
```

**Comment by z3dev** [comment]
This functionality is now present and tested in V2. Closing.
