### ISSUE TITLE
lint rules for the code?

### ISSUE THREAD

**Issue by drom** [jscad/io#36]
Do you have any eslint rules config for the project?

**Comment by z3dev** [comment]
TIPS for successful pull requests:

- Commit often, and comment well
- Follow the JavaScript Standard Style
- Create test cases for all changes
- Verify that all tests suites pass

That's about all...

**Comment by drom** [comment]
Got it!

**Comment by kaosat-dev** [comment]
No eslint please as that is not what we use but feel free to add standardjs https://standardjs.com/ to npm test please ;-)

**Comment by drom** [comment]
@kaosat-dev 
As I understand, https://github.com/standard/eslint-config-standard
Is direct `eslint` config from StandardJS https://github.com/standard
https://github.com/standard/standard is just BIG wrapper based on the same `eslint` inside.
I am working on ton of different JS packages, and having `eslint` with specific config is standard ways of switching between projects. And all my editors like Atom with `eslint` plugin understand this very well.

**Comment by kaosat-dev** [comment]
@drom hmm you make a good point, then again, what I like about standard is that you do not need to add *yet another* config file to a repo ...simplicity is important given the scope of the project.
I'll experiment a bit first if you do not mind ? 
One advantage of having it in a monorepo is that we could get away of having a single `.eslintrc` perhaps?  (one in every package is overkill)

**Comment by drom** [comment]
Adding PR for the simplest way of using standard style as I see it.

**Comment by kaosat-dev** [comment]
ok , latest PR looks good & merged, so closing this.
