### ISSUE TITLE
DOM model for SVG serializer

### ISSUE THREAD

**Issue by drom** [jscad/io#38]
Per discussion in #23 ...

@kaosat-dev right now in svg-serializer you construct output SVG as string, by concatenating smaller strings. As code grows it will be harder and harder to maintain string concatenation approach.
Here are three possible improvements I see from here:

use xmldom like you do in x3d-serializer
construct JSONML http://www.jsonml.org/ like object and then serialize it into string. I have simple library that would work: https://github.com/drom/onml
use React to construct component structure and then use https://reactjs.org/docs/react-dom-server.html to renderToString()

**Comment by z3dev** [comment]
@drom I'm not very particular about which library is used to create XML, but I would hope we can decide on a single library, as there will be several 'serializers' that create XML.

How about making the changes in your repo, and then let us review the code?

**Comment by drom** [comment]
@z3dev I have created #39 as example.
Yes, all XML serializes can be done using ONML

**Comment by kaosat-dev** [comment]
I really like how it works, very declarative (repeating myself), at least for serializers, my mind is too hazy tonight for deserializers haha

**Comment by drom** [comment]
@kaosat-dev I can make ONML version of one of XML-like de-serializers as example

**Comment by kaosat-dev** [comment]
I am closing this as this is now integrated !
Thanks @drom  , feeling like doing the same for some of the other (de)-serializers ? :)

**Comment by z3dev** [comment]
@drom Please do!

**Comment by drom** [comment]
@kaosat-dev @z3dev yes, I am looking into converting one of de-serializers into ONML.

**Comment by z3dev** [comment]
@drom Cool! Thanks.
