### ISSUE TITLE
Add support for arrays as inputs to serializers

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/io#56]
- This would allow us to not force a costly union() of arrays returned by the main() function.
- It would require the ability to 'concatenate' geometric data in the output files.
- [x] First and foremost we need stl output support 
- [ ] We also might need to warn the user that the output will not be guaranteed to be manifold
- [ ] alternative implementation : turned union of non overlapping objects into almost a no-op

**Comment by z3dev** [comment]
Done as part of V2.
