### ISSUE TITLE
V2 Rework and Enhancements

### ISSUE THREAD

**Issue by z3dev** [jscad/io#64]
The CSG library V2 API will require changes to the IO libraries. This issue tries to summarize the changes expected.

Changes from CSG V2
- Use CSG V2 core API and classes internally
- Translate to CSG V2 source code; use V2 API calls, code restructure if necessary
- Instantiate CSG V2 classes for return

Enhancements to IO V2
- serialize() functions to accept an array of objects (Closes #56)
  - reorder parameters to serialize( options, ...objects )
- deserialize() functions to return an array of objects
- improved test cases; simple in-line tests (Closes #23)
- symetrical serialize and deserialize of objects

**Comment by kaosat-dev** [comment]
This is great ! Given that we are not even close to the v2.0 of csg.js , this could take a while, but I can only approve of all those improvements :)

**Comment by z3dev** [comment]
Addressed as part of V2, so closing this issue.
