### ISSUE TITLE
SVG export creates unrelated paths

### ISSUE THREAD

**Issue by z3dev** [jscad/io#7]
_From @matthijskooijman on February 26, 2017 11:9_

I just tested the SVG export briefly and noticed that it seems to create separate paths instead of combined paths when the latter would be more appropriate. I'll explain using an example:

This code:
```
function main() {
	return CAG.circle({radius: 4}).subtract(CAG.circle({radius: 1}));
}
```

Creates this rendering:

![selection_002](https://cloud.githubusercontent.com/assets/194491/23339100/41c283a0-fc1b-11e6-935b-9a4068823a97.png)

But when exporting this to SVG, it creates two separate paths, which both have a fill set:

![selection_003](https://cloud.githubusercontent.com/assets/194491/23339122/9ecc8e10-fc1b-11e6-8c38-9b27b07156a6.png)

The left shows the SVG as exported, opened in inkscape. The right shows the same file, but with the fill replaced by a stroke. It also shows that the two paths are separate, each has its own selection box.

When both paths would be combined into a single path (as they are in the original, a single CAG), the filling would be appropriately applied to inside of the bigger circle, but outside of the smaller circle. If you do this in Inkscape by selecting both circles and clicking path->combine, then you get the expected result:

![selection_004](https://cloud.githubusercontent.com/assets/194491/23339142/ff2573b2-fc1b-11e6-8d5a-e511f5c07661.png)

The easiest way to implement this is probably to export a single CAG as a single path in the resulting SVG. A better way would be to only do this when needed and turn completely unrelated parts of a drawing into separate paths for easier editing later on. I think this would mean to divide all paths in the CAG into non-overlapping groups and exporting a path for each of these groups, but I'm not quite sure this is sufficient.

_Copied from original issue: Spiritdude/OpenJSCAD.org#229_

**Comment by z3dev** [comment]
@matthijskooijman V2 will be exporting 2D geometry (now called geom2, previously called CAG) to a continous path. For example, here's the path for the example provided.

`<path fill-rule="evenodd" fill="rgb(127.5,127.5,127.5,127.5)" d="M20 10L19.2388 13.8268L17.0711 17.0711L13.8268 19.2388L10 20L6.1732 19.2388L2.9289 17.0711L0.7612 13.8268L0 10L0.7612 6.1732L2.9289 2.9289L6.1732 0.7612L10 0L13.8268 0.7612L17.0711 2.9289L19.2388 6.1732L20 10M12.7716 8.852L12.1213 7.8787L11.1481 7.2284L10 7L8.852 7.2284L7.8787 7.8787L7.2284 8.852L7 10L7.2284 11.1481L7.8787 12.1213L8.852 12.7716L10 13L11.1481 12.7716L12.1213 12.1213L12.7716 11.1481L13 10L12.7716 8.852"/>`

**Comment by matthijskooijman** [comment]
Cool, thanks!

**Comment by z3dev** [comment]
@matthijskooijman how does this SVG look? this is from the V2 SVG serializer (export) function.

[issue7.svg.txt](https://github.com/jscad/io/files/4496259/issue7.svg.txt)

**Comment by matthijskooijman** [comment]
Looks perfect! If that is what is currently implemented, I think this issue can be closed as fixed :-)

**Comment by z3dev** [comment]
That’s the implementation!
Thanks!
