### ISSUE TITLE
SVG : deserializer does not preserve holes

### ISSUE THREAD

**Issue by pentacular** [jscad/io#71]
SVG with holes is deserialized to CSG or jscad code without the holes.

Test case included below

-- SVG input --

  <svg height="297" width="210">
  <path d="M 325.71484 233.94922 A 122.85714 108.57142 0 0 0 202.85742 342.51953 A 122.85714 108.57142 0 0 0 325.71484 451.0918 A 122.85714 108.57142 0 0 0 448.57227 342.51953 A 122.85714 108.57142 0 0 0 325.71484 233.94922 z M 328.57227 308.23438 A 54.285711 35.714286 0 0 1 382.85742 343.94727 A 54.285711 35.714286 0 0 1 328.57227 379.66211 A 54.285711 35.714286 0 0 1 274.28516 343.94727 A 54.285711 35.714286 0 0 1 328.57227 308.23438 z " style="stroke: #006666; fill: none;"/>
  </svg>

-- JSCAD output --

function main(params) {
  var cag0 = new CAG();
  var cag00 = new CAG();
  var cag001 = new CSG.Path2D([[91.92395871744799,-66.025663556684]],false);
  cag001 = cag001.appendArc([57.250867358723994,-96.66661529956598],{xradius: 34.673012336507995,yradius: -30.641265009524,xaxisrotation: 0,clockwise: false,large: false});
  cag001 = cag001.appendArc([91.92395871744799,-127.30812019795998],{xradius: 34.673012336507995,yradius: -30.641265009524,xaxisrotation: 0,clockwise: false,large: false});
  cag001 = cag001.appendArc([126.59705289839398,-96.66661529956598],{xradius: 34.673012336507995,yradius: -30.641265009524,xaxisrotation: 0,clockwise: false,large: false});
  cag001 = cag001.appendArc([91.92395871744799,-66.025663556684],{xradius: 34.673012336507995,yradius: -30.641265009524,xaxisrotation: 0,clockwise: false,large: false});
  cag001 = cag001.close();
  cag001 = cag001.innerToCAG();
  cag00 = cag00.union(cag001);
  var cag002 = new CSG.Path2D([[92.730388898394,-86.99058483923599]],false);
  cag002 = cag002.appendArc([108.05086335872399,-97.06955522339399],{xradius: 15.320632786984199,yradius: -10.0793643663492,xaxisrotation: 0,clockwise: true,large: false});
  cag002 = cag002.appendArc([92.730388898394,-107.14907594084198],{xradius: 15.320632786984199,yradius: -10.0793643663492,xaxisrotation: 0,clockwise: true,large: false});
  cag002 = cag002.appendArc([77.409361282552,-97.06955522339399],{xradius: 15.320632786984199,yradius: -10.0793643663492,xaxisrotation: 0,clockwise: true,large: false});
  cag002 = cag002.appendArc([92.730388898394,-86.99058483923599],{xradius: 15.320632786984199,yradius: -10.0793643663492,xaxisrotation: 0,clockwise: true,large: false});
  cag002 = cag002.close();
  cag002 = cag002.innerToCAG();
  cag00 = cag00.union(cag002);
  cag0 = cag0.union(cag00);
  return cag0;
}

**Comment by z3dev** [comment]
Yes. That's correct. It's up to the user to pull apart the outlines, and create the appropriate CAG.

It may be possible to determine the inside pieces from the rotation of the outline. What do you think?

**Comment by pentacular** [comment]
Yeah, that's the conclusion I came to -- at least for compound paths.

Since there don't seem to be any better ideas, I'll put together a fix in a bit.

**Comment by z3dev** [comment]
I remember reading something in the SVG specification as well, but it was more of guidance rather than a standard.

**Comment by kaosat-dev** [comment]
fill rule + csg/cag is kind of a nightmare (implemented it for work), so any fix is good fix in this case @pentacular , thanks :)

**Comment by pentacular** [comment]
I've added a fix in https://github.com/jscad/io/pull/70
But that fix depends on https://github.com/jscad/csg.js/pull/116 to build.

Let me know if that needs some special care to untangle.

**Comment by z3dev** [comment]
This issues has been fixed as part of #70
