### ISSUE TITLE
OFF : create deserializer and serializer

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/io#81]
Based on @gilboonet 's great work (hi :) we can add an OFF deserializer : https://github.com/gilboonet/OFF2JSCAD/blob/master/off2csg.jscad
Everything is already in there, so this should be rather easy work (following the template of other deserialisers).
Should be relatively beginner friendly too , (with our help when needed :)

**Comment by gilboonet** [comment]
Hello, I've started to do this deserializer, following the template of OBJ deserializer, that made me change 2 files :
- ../packages/web/src/io/conversionWorker.js
- ../packages/core/io/formats.js
and add a directory ../packages/core/node_modules/@jscad/off-deserializer
where I created index.js

Can someone tell me what I must do now ? Or is there a doc explaining the process ? maybe someone already ask the same and there is an issue with such info ?
![capture d ecran de 2019-01-10 10-57-00](https://user-images.githubusercontent.com/22082873/50960813-83deaf00-14c6-11e9-9d48-9f4b0c5cbe47.png)

**Comment by z3dev** [comment]
@gilboonet Welcome!

I suggest working on the serializer abalone first. After downloading the IO library, just run ‘NPM bootstrap’. That should setup all the dependence’s for the existing serializers. You can then switch to any of the sub-pagakes and run ‘NPM test’. (I may have a few things wrong but keep trying.)

You should be able to then copy the OBJ deserializer, and make changes for the OFF format.

Oh! We have a repository of test files as well. It would be great if you put any required OFF files there.

**Comment by gilboonet** [comment]
Hello, I'm slowly discovering github development. I forked IO and added an OFF deserializer, created its index.js with a custom getPositionsAndFaces. And I also added test.js with a changed inputPath. I cloned @jscad/sample-files and added a directory OFF to it where I put a cube.off that I converted from cube.obj. When I run "npm test" I have an error saying "no such file or directory"
![capture d ecran de 2019-01-16 14-53-45](https://user-images.githubusercontent.com/22082873/51253765-8d24bb80-199f-11e9-8d99-c14225b0feb2.png)

Do I need to commit the changes I made ? something like git commit ?
Do I also need to fork @jscad/sample-files ?

**Comment by z3dev** [comment]
You will have to fork IO and samples. When done, just create a pull request back to JSCAD, and we will review.

**Comment by z3dev** [comment]
For tests, I suggest creating very small test cases. Each test case should cover only specific conversions. Just pass a string to the serializer. See the DXF tests.

Once you have good coverage, then you can use real OFF files from various sources, and verify the conversion works as expected.

**Comment by z3dev** [comment]
By the way, I’m available via Hangouts, located in Japan. Grab me if you want faster help. jeff.gay @ z3d.jp
You’re doing a great job so keep at it!

**Comment by gilboonet** [comment]
I made a first attempt with a OFF file and test.js has errors but I don't see how to investigate
![capture d ecran de 2019-01-17 13-24-55](https://user-images.githubusercontent.com/22082873/51318818-a3904d00-1a5b-11e9-9836-931b05c16cd3.png)

Maybe did I go too fast and like you suggested I will try with string before using an real OFF file.

**Comment by z3dev** [comment]
@gilboonet Any progress? Stuck?

**Comment by gilboonet** [comment]
![capture d ecran de 2019-01-26 18-00-52](https://user-images.githubusercontent.com/22082873/51790440-b0b4e680-2195-11e9-82cd-d562a1b611fc.png)
It's ok now, with the simple cube off file. I had a bug due to reverse order of faces between off and csg. So it needs more test with other files.

**Comment by gilboonet** [comment]
@z3dev I tried to go further with this deserializer and wanted to link my local version of OpenJSCAD.org to it (by npm link) but it doesn't seem to work. Is there a post or a page somewhere where I can find how to do that ? (I already made the changes to openJSCAD.org files conversionWorkerjs, formats.js and index.html to add off format)

**Comment by z3dev** [comment]
@gilboonet Sorry for the late reply.

I suggest writing test cases that cover all functionality (that you want), and make those tests pass using ‘node test’. Make each test simple, covering a specific shape or functional piece. Lots of little test suites (files) is better then one big monster.

Once you get a complete deserializer/ serializer working and tested, then we can integrate. The integration is not a simple step. :(

**Comment by kaosat-dev** [comment]
to add to what @z3dev said I think we should be a lot more easilly able to tackle this once V2 is finally out of the door (sorry it is taking us ages :( ) lots more time for all the serializers & co ! :)

**Comment by z3dev** [comment]
Closing as this has been moved to jscad/OpenJSCAD.org#753
