### ISSUE TITLE
Is it possible to use this repository whithout Node?

### ISSUE THREAD

**Issue by Valeriy-Apostolyuk** [jscad/io#84]
Hello, I'm trying to build a web site that requires a stl input from the user, and I need to convert the stl format into jscad, is it possible to use this repository without installing node, and if yes, how can i get the generated jscad code?

Thank you.

**Comment by z3dev** [comment]
@Valeriy-Apostolyuk Sorry for the late reply.

First, you should be able to put together something. Keep in mind that these little modules require other modules, such as the CSG library. You can download each and paste together, or you can use NPM to download each and use browserify to paste together.

Quick question... once you have the jscad code... then what do you want to do? View the design?
